# Generated by Django 5.2.15 on 2026-06-14 02:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='monthly_budget_threshold',
        ),
        migrations.AddField(
            model_name='category',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
